name: Sync Staging to Master
on:
  push:
    branches:
      - 'staging'
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge Staging -> Master
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: staging
          target_branch: master
          github_token: ${{ github.token }}